import 'dotenv/config';
import express from 'express';

const app = express()
app.use(express.json())

const PORT = process.env.PORT;

app.listen(PORT, async () => {
    console.log(`Server listening on port ${PORT}...`);
})

app.post('/billboard', async(req, res) => {
    const albumNum = req.body.number - 1
    console.log("Recieved the number: ", albumNum + 1)
    const topOneHundred = 
    [
    "Dangerous: The Double Album by Morgan Wallen",
    "21 by Adele",
    "Fearless by Taylor Swift",
    "1989 by Taylor Swift",
    "Hamilton: An American Musical by Original Broadway Cast Recording",
    "One Thing At A Time by Morgan Wallen",
    "Hollywood's Bleeding by Post Malone",
    "My Turn by Lil Baby",
    "All The Right Reasons by Nickelback",
    "The Fame by Lady Gaga",
    "Divide by Ed Sheeran",
    "beerbongs & bentleys by Post Malone",
    "Christmas by Michael Buble",
    "Lover by Taylor Swift",
    "Confessions by Usher",
    "Frozen by Frozen Movie Soundtrack",
    "When We All Fall Asleep, Where Do We Go? by Billie Eilish",
    "Taylor Swift by Taylor Swift",
    "Some Hearts by Carrie Underwood",
    "Sour by Olivia Rodrigo",
    "[Hybrid Theory] by Linkin Park",
    "Come Away With Me by Norah Jones",
    "Daughtry by Daughtry",
    "Stoney by Post Malone",
    "DAMN. by Kendrick Lamar",
    "SOS by SZA",
    "Night Visions by Imagine Dragons",
    "Views by Drake",
    "Midnights by Taylor Swift",
    "Traveller by Chris Stapleton",
    "Shoot For The Stars Aim For The Moon by Pop Smoke",
    "Un Verano Sin Ti by Bad Bunny",
    "Fallen by Evanescence",
    "X by Ed Sheeran",
    "This One's For You by Luke Combs",
    "Scorpion by Drake",
    "Folklore by Taylor Swift",
    "Goodbye & Good Riddance by Juice WRLD",
    "The Eminem Show by Eminem",
    "Blurryface by Twenty One Pilots",
    "ASTROWORLD by Travis Scott",
    "In The Lonely Hour by Sam Smith",
    "High School Musical by High School Musical Movie Soundtrack",
    "What You See Is What You Get by Luke Combs",
    "The Emancipation Of Mimi by Mariah Carey",
    "Unorthodox Jukebox by Bruno Mars",
    "Let Go by Avril Lavigne",
    "Human Clay by Creed",
    "Rock N Roll Jesus by Kid Rock",
    "25 by Adele",
    "Need You Now by Lady A",
    "The Highlights by The Weeknd",
    "Curtain Call: The Hits by Eminem",
    "Here's To The Good Times by Florida Georgia Line",
    "American Idiot by Green Day",
    "24K Magic by Bruno Mars",
    "Hannah Montana 2 (Soundtrack)/ Meet Miley Cyrus by Miley Cyrus",
    "Breakaway by Kelly Clarkson",
    "My World 2.0 by Justin Bieber",
    "1 by The Beatles",
    "Hotshot by Shaggy",
    "Country Grammar by Nelly",
    "The Greatest Showman by The Greatest Showman Movie Soundtrack",
    "Starboy by The Weeknd",
    "Certified Lover Boy by Drake",
    "Recovery by Eminem",
    "The E.N.D. by The Black Eyed Peas",
    "FutureSex/LoveSounds by Justin Timberlake",
    "Take Care by Drake",
    "ANTI by Rihanna",
    "Crash My Party by Luke Bryan",
    "The Dutchess by Fergie",
    "O Brother, Where Art Thou? by O Brother, Where Art Thou? Movie Soundtrack",
    "Me And My Gang by Rascal Flatts",
    "Sigh No More by Mumford & Sons",
    "Songs In A Minor by Alicia Keys",
    "No Strings Attached by *NSYNC",
    "Speakerboxxx/The Love Below by OutKast",
    "After Hours by The Weeknd",
    "Babel by Mumford & Sons",
    "good kid, m.A.A.d city by Kendrick Lamar",
    "As I Am by Alicia Keys",
    "Legends Never Die by Juice WRLD",
    "Monkey Business by The Black Eyed Peas",
    "Red by Taylor Swift",
    "Planet Her by Doja Cat",
    "Get Rich Or Die Tryin' by 50 Cent",
    "My Kinda Party by Jason Aldean",
    "Home by The Chicks",
    "Konvicted by Akon",
    "Back To Black by Amy Winehouse",
    "Tha Carter III by Lil Wayne",
    "A Day Without Rain by Enya",
    "M!ssundaztood by Pink",
    "Stick Season by Noah Kahan",
    "Fine Line by Harry Styles",
    "Silver Side Up by Nickelback",
    "Future Nostalgia by Dua Lipa",
    "Supernatural by Santana",
    "Beauty Behind The Madness by The Weeknd",
    ]
    console.log("Responded with the album: ", topOneHundred[albumNum])   
    res.status(201).json(topOneHundred[albumNum])
})